runtime: python39
entrypoint: serve index.html

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /styles\.css
  static_files: styles.css
  upload: styles.css

- url: /(.*)
  static_files: \1
  upload: .*
